// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  docSidebar: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'start/index',
        'start/installation',
        'start/web-servers',
        'deployment/deployment',
        'start/upgrade',         
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'concepts/index',
      },
      items: [
        'concepts/life-cycle',
        'concepts/value-objects',
        'concepts/middleware',
        'concepts/di',
      ],
    },
    {
      type: 'category',
      label: 'The Application',
      collapsed: true,
      items: [
        'objects/application',
      ],
    },    
    {
      type: 'category',
      label: 'HTTP Messages',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'objects/index',
      },
      items: [
        'objects/request',
        'objects/response',
      ],
    },
    {
      type: 'category',
      label: 'Routing',
      collapsed: true,
      items: [
        'objects/routing',
      ],
    },
    {
      type: 'category',
      label: 'Packaged Middleware',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'middleware/index',
      },
      items: [
        'middleware/routing',
        'middleware/error-handling',
        'middleware/method-overriding',
        'middleware/output-buffering',
        'middleware/body-parsing',
        'middleware/content-length',
      ],
    },
    {
      type: 'category',
      label: 'Cook book',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'cookbook/index',
      },
      items: [
        'cookbook/route-patterns',
        'cookbook/retrieving-current-route',
        'cookbook/database-doctrine',
        'cookbook/enable-cors',
        'cookbook/uploading-files',
      ],
    },
    {
      type: 'category',
      label: 'Add Ons',
      collapsed: true,
      items: [
        'features/templates',
        'features/twig-view',
        'features/php-view',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'contributors/index',
      },
      items: [
        'contributors/strategy',
        'contributors/guidelines',
      ],
    },    
  ],   
};

export default sidebars;
